version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    logging:
      driver: none
    environment:
      POSTGRES_USER: 'fede'
      POSTGRES_DB: 'test'
      POSTGRES_PASSWORD: '12345'
